Add cn_validations property to pki_secret_backend_role
hashicorp/terraform-provider-vault pull request #1820
Opened 2023-04-14 15:28 UTC by bmhughes

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vault/blob/master/CHANGELOG.md):

```release-note
- Add cn_validations property to pki_secret_backend_role
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2023-06-09 15:10 UTC, fairclothjm commented
closes https://github.com/hashicorp/terraform-provider-vault/issues/1883

2023-08-03 11:17 UTC, bmhughes commented
Rebased on current `main`

2024-11-26 15:42 UTC, stevendpclark requested changes
Thanks @bmhughes for this contribution!

Would you mind updating the PR against main, addressing my small ask around augmenting the tests. Also we will need a changelog entry within CHANGELOG.md, something like this would do.

```
* Update `vault_pki_secret_backend_role` to support the `cn_validations` role field ([#1820](https://github.com/hashicorp/terraform-provider-vault/pull/1820)).
```

2024-11-26 15:42 UTC, stevendpclark commented on vault/resource_pki_secret_backend_role_test.go
> +  cn_validations					 = ["email", "hostname"]
Can we add assertions that the values are being set properly. Something like this for the initial checks 

```
resource.TestCheckResourceAttr(resourceName, "cn_validations.#", "2"),
resource.TestCheckTypeSetElemAttr(resourceName, "cn_validations.*", "email"),
resource.TestCheckTypeSetElemAttr(resourceName, "cn_validations.*", "hostname"),
```

And this for when we update the role within the test?

```
resource.TestCheckResourceAttr(resourceName, "cn_validations.#", "1"),
resource.TestCheckTypeSetElemAttr(resourceName, "cn_validations.*", "disabled"),
```

2024-11-26 16:11 UTC, bmhughes commented
Hi @stevendpclark, thanks for the feedback. I've implemented those changes, let me know if there's anything else!

2024-11-26 16:42 UTC, stevendpclark approved these changes
Wonderful thanks @bmhughes!

2024-11-26 16:42 UTC, merged