Add iam_tags to vault_aws_secret_backend_role resource
hashicorp/terraform-provider-vault pull request #2087
Opened 2023-11-15 13:45 UTC by pporee

### Description

Relates OR Closes #0000

### Checklist
- [ ] Added [CHANGELOG](https://github.com/hashicorp/terraform-provider-vault/blob/master/CHANGELOG.md) entry (only for user-facing changes)
- [ ] Acceptance tests where run against all supported Vault Versions

### Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

2023-11-15 13:45 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-provider-vault?pullRequest=2087)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-provider-vault?pullRequest=2087)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-provider-vault?pullRequest=2087).</sub>

2023-11-17 05:39 UTC, thyton requested changes
Hi @pporee, this PR seems to break some of the acceptance tests (see below for an example). Local test setup guides can be found at https://github.com/hashicorp/terraform-provider-vault/blob/main/README.md#developing-the-provider. Could you take a look and drop your acceptance tests' output in the description like [#781's](https://github.com/hashicorp/terraform-provider-vault/pull/781#issue-626071588)?
 
Please let us know if you need any help.

Thanks,
Thy

2023-11-17 05:39 UTC, thyton commented on vault/resource_aws_secret_backend_role_test.go
> +	  }
```suggestion
  iam_tags = {
    "key1" = "value1"
    "key2" = "value2"
  }
```

2024-04-14 22:47 UTC, Shocktrooper commented
Hello! I am interested in this because it will allow us to use AWS policy variables in our IAM policies.  Without this we cannot do that and thus cannot use AWS Policy variables based off of tags
- https://docs.aws.amazon.com/IAM/latest/UserGuide/access_tags.html

2024-04-14 22:50 UTC, Shocktrooper commented
@thyton Can you check this code again and see if there are any other changes needed other than what you have reviewed since its a few months old now.  if @pporee cannot complete this I can go ahead and try to finish it with a new MR

2024-04-30 19:12 UTC, thyton commented
@Shocktrooper Thank you for your patience! I've created a WIP #2231 to finish the remaining work and close this PR.
I'm expecting to close #2231 within 2 weeks.

2024-04-30 19:12 UTC, closed without merging

2024-05-01 01:31 UTC, Shocktrooper commented
Thank you for picking this up! @thyton  Let me know if there is anything I can do

2024-05-01 21:23 UTC, thyton commented
@pporee @Shocktrooper This feature will be out in release [4.3.0](https://github.com/hashicorp/terraform-provider-vault/milestone/50). Thank you again for your patience!