Add support for CMPv2 configuration
hashicorp/terraform-provider-vault pull request #2330
Opened 2024-09-19 21:28 UTC by rculpepper

### Description

Relates OR Closes #0000

### Checklist
- [ ] Added [CHANGELOG](https://github.com/hashicorp/terraform-provider-vault/blob/master/CHANGELOG.md) entry (only for user-facing changes)
- [ ] Acceptance tests where run against all supported Vault Versions

### Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

2024-09-20 14:17 UTC, stevendpclark commented on website/docs/d/pki_secret_backend_config_cmpv2.html.md
> +* `authenticators` - Lists the mount accessors EST should delegate authentication requests towards (see [below for nested schema](#nestedatt--authenticators)).
```suggestion
* `authenticators` - Lists the mount accessors CMPv2 should delegate authentication requests towards (see [below for nested schema](#nestedatt--authenticators)).
```

2024-09-20 14:17 UTC, stevendpclark commented on website/docs/d/pki_secret_backend_config_cmpv2.html.md
> +  read the EST configuration from, with no leading or trailing `/`s.
```suggestion
  read the CMPv2 configuration from, with no leading or trailing `/`s.
```

2024-09-20 14:19 UTC, stevendpclark commented on website/docs/d/pki_secret_backend_config_cmpv2.html.md
> +* `default_path_policy` - Required to be set if default_mount is enabled. Specifies the behavior for requests using the default EST label. Can be sign-verbatim or a role given by role:<role_name>.
```suggestion
* `default_path_policy` - Specifies the behavior for requests using the non-role-qualified CMPv2 requests. Can be sign-verbatim or a role given by role:<role_name>.
```

2024-09-20 14:19 UTC, stevendpclark commented on website/docs/d/pki_secret_backend_config_cmpv2.html.md
> +* `enabled` - Specifies whether EST is enabled.
```suggestion
* `enabled` - Specifies whether CMPv2 is enabled.
```

2024-09-20 18:49 UTC, sgmiller requested changes
Looks good except for the c/p typos Steve noted.

2024-11-18 17:37 UTC, stevendpclark submitted a review, later dismissed
👍

2024-12-06 17:13 UTC, sgmiller submitted a review, later dismissed
Assuming tests pass LGTM

2024-12-09 18:23 UTC, merged